/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Entidades.Vacuna;
import accesoADatos.Conexion;
import accesoADatos.VacunaData;
import java.sql.Connection;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author manue
 */
public class VacunaDemo extends javax.swing.JPanel {

    private VacunaData vacunaData;
    private Vacuna vacuna;
    private Connection conexion = null;

    /**
     * Creates new form VacunaDemo
     */
    public VacunaDemo() {

        initComponents();
        vacuna = new Vacuna();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPvacuna = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTnumSerie = new javax.swing.JTextField();
        jTaplicada = new javax.swing.JTextField();
        jBagregar = new javax.swing.JButton();
        jBbuscar = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jTvencimiento = new javax.swing.JTextField();
        jBeliminar1 = new javax.swing.JButton();
        jComboMarca = new javax.swing.JComboBox<>();
        jComboDosis = new javax.swing.JComboBox<>();

        JPvacuna.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de Vacuna");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("Medida");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("Numero de Serie");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("Marca");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setText("Vencimiento");

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("Aplicada");

        jTnumSerie.setBackground(new java.awt.Color(102, 204, 255));

        jTaplicada.setBackground(new java.awt.Color(102, 204, 255));

        jBagregar.setBackground(new java.awt.Color(168, 206, 232));
        jBagregar.setText("Agregar");
        jBagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarActionPerformed(evt);
            }
        });

        jBbuscar.setBackground(new java.awt.Color(168, 206, 232));
        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jBmodificar.setBackground(new java.awt.Color(168, 206, 232));
        jBmodificar.setText("Modificar");

        jBeliminar.setBackground(new java.awt.Color(168, 206, 232));
        jBeliminar.setText("Eliminar");

        jTvencimiento.setBackground(new java.awt.Color(102, 204, 255));

        jBeliminar1.setBackground(new java.awt.Color(168, 206, 232));
        jBeliminar1.setText("StockDisponible");

        jComboMarca.setBackground(new java.awt.Color(102, 204, 255));
        jComboMarca.setForeground(new java.awt.Color(0, 0, 102));
        jComboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moderna", "Pfizer", "AstraZeneca", "Sinopharm", "Sputnik" }));
        jComboMarca.setBorder(null);

        jComboDosis.setBackground(new java.awt.Color(102, 204, 255));
        jComboDosis.setForeground(new java.awt.Color(0, 0, 102));
        jComboDosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.3 ml", "0.5 ml", "0.9 ml" }));
        jComboDosis.setBorder(null);

        javax.swing.GroupLayout JPvacunaLayout = new javax.swing.GroupLayout(JPvacuna);
        JPvacuna.setLayout(JPvacunaLayout);
        JPvacunaLayout.setHorizontalGroup(
            JPvacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPvacunaLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addGap(311, 311, 311))
            .addComponent(jSeparator1)
            .addGroup(JPvacunaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(JPvacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(JPvacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTaplicada, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(jTnumSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(jTvencimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(jComboMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboDosis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(123, 123, 123)
                .addGroup(JPvacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBeliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPvacunaLayout.createSequentialGroup()
                        .addGroup(JPvacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBeliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBagregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(92, 92, 92))
        );
        JPvacunaLayout.setVerticalGroup(
            JPvacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPvacunaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPvacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPvacunaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTnumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JPvacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jComboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPvacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPvacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTvencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPvacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBeliminar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTaplicada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(174, 174, 174))
        );

        jTabbedPane1.addTab("Vacuna", JPvacuna);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed

        int numSerie = Integer.parseInt(jTnumSerie.getText());

        Vacuna vacunaEncontrada = vacunaData.obtenerVacunaPorNroSerie(numSerie);

        if (vacunaEncontrada != null) {
            
            String marca = jComboMarca.getSelectedItem().toString();     // referenciar comboMarca
            
            String medida = jComboDosis.getSelectedItem().toString();     // referenciar comboDosis                
            java.sql.Date fechaCaducidad = vacunaEncontrada.getFechaCaduca(); // Suponiendo que vacunaEncontrada.getFechaCaduca() devuelve un objeto java.sql.Date
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Crear un objeto SimpleDateFormat para formatear la fecha// Puedes usar el formato que desees
            String fechaComoString = sdf.format(fechaCaducidad); // Formatear la fecha como una cadena de texto
            jTvencimiento.setText(fechaComoString); // Establecer la cadena de texto en tu componente jTvencimiento            
            jTaplicada.setText(Boolean.toString(vacunaEncontrada.isColocada()));
            if (vacunaEncontrada.isColocada() == true) {
                jTaplicada.setText("colocada");
            } else {
                jTaplicada.setText("NO colocada");
            }

        } else {
            JOptionPane.showMessageDialog(this, "vacuna no encontrada!.    ⚠", "", JOptionPane.ERROR_MESSAGE);
            limpiarCampos();
        }


    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jBagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarActionPerformed
                
        int numSerie;
        try {
            numSerie=Integer.parseInt(jTnumSerie.getText().trim()); // valida solo numeros       
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El n° de Serie debe contener solo números!.   ⚠", "", JOptionPane.ERROR_MESSAGE);
            return;         
            }
        limpiarCampos();
        
        Vacuna vacunaEncontrada = vacunaData.obtenerVacunaPorNroSerie(numSerie);  // valida vacuna duplicada
        
        if (vacunaEncontrada !=null){
            JOptionPane.showMessageDialog(this, "este n° de Serie ya existe!.  ⚠", "", JOptionPane.ERROR_MESSAGE);
            limpiarCampos();
           
        String marca = jComboMarca.getSelectedItem().toString();     // referenciar comboMarca
        String medida = jComboDosis.getSelectedItem().toString();
        java.sql.Date fechaCaducidad = vacunaEncontrada.getFechaCaduca(); // Suponiendo que vacunaEncontrada.getFechaCaduca() devuelve un objeto java.sql.Date
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Crear un objeto SimpleDateFormat para formatear la fecha// Puedes usar el formato que desees
        String fechaComoString = sdf.format(fechaCaducidad); // Formatear la fecha como una cadena de texto
        jTvencimiento.setText(fechaComoString); // Establecer la cadena de texto en tu componente jTvencimiento
        jTaplicada.setText(Boolean.toString(vacunaEncontrada.isColocada()));
            if (vacunaEncontrada.isColocada() == true) {
                jTaplicada.setText("colocada");
            } else {
                jTaplicada.setText("NO colocada");
            }    
        } else {
            JOptionPane.showMessageDialog(this, "vacuna no encontrada!.    ⚠", "", JOptionPane.ERROR_MESSAGE);
            limpiarCampos();
        }
        
        
        
  

        
        

    }//GEN-LAST:event_jBagregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPvacuna;
    private javax.swing.JButton jBagregar;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBeliminar1;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JComboBox<String> jComboDosis;
    private javax.swing.JComboBox<String> jComboMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTaplicada;
    private javax.swing.JTextField jTnumSerie;
    private javax.swing.JTextField jTvencimiento;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {}
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Centro de Vacunación");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(900, 500);

            VacunaDemo panelVacuna = new VacunaDemo();
            frame.add(panelVacuna);

            frame.setVisible(true);
        });
    }
}
