package vistas2;

import Entidades.CentroVacunacion;
import accesoADatos.CentroVacunacionData;
import accesoADatos.Conexion;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilidades.ProvinciasCiudades;

/**
 *
 * @author Gonz@_
 */
public class CentroVacunacionVista_2 extends javax.swing.JPanel {

    private CentroVacunacionData centroVacunacionData;
   private DefaultTableModel modelo;

    /**
     * Creates new form CentroVacunacion_2
     */
    public CentroVacunacionVista_2() {
        initComponents();
        cargarProvincias();
        centroVacunacionData = new CentroVacunacionData(Conexion.getConexion());
        modelo = new DefaultTableModel();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_centroVac_fondo = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_centroVac = new javax.swing.JPanel();
        jPanel_centro_vac = new javax.swing.JPanel();
        txt_centroVacunacion_id = new javax.swing.JTextField();
        txt_nombre_centroVacunacion = new javax.swing.JTextField();
        txt_direccion_centroVac = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jCB_CentroVacunacion_Provincias = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jCB_CentroVacunacion_Ciudades = new javax.swing.JComboBox<>();
        jPanel_titulo_ciudadano1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jBBuscar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jPanel_listar_ciudadano = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txt_centroVacunacion_buscar = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ciudadano_tabla = new javax.swing.JTable();
        jPanel_titulo_ciudadano2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        btn_centroVacunacion_nuevo = new javax.swing.JButton();

        jPanel_centroVac_fondo.setBackground(new java.awt.Color(137, 161, 209));

        jTabbedPane1.setBackground(new java.awt.Color(191, 200, 209));
        jTabbedPane1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        jPanel_centroVac.setBackground(new java.awt.Color(59, 66, 109));

        jPanel_centro_vac.setBackground(new java.awt.Color(191, 200, 209));
        jPanel_centro_vac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_centroVacunacion_id.setBackground(new java.awt.Color(137, 161, 209));
        jPanel_centro_vac.add(txt_centroVacunacion_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, 30));

        txt_nombre_centroVacunacion.setBackground(new java.awt.Color(137, 161, 209));
        jPanel_centro_vac.add(txt_nombre_centroVacunacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, 30));

        txt_direccion_centroVac.setBackground(new java.awt.Color(137, 161, 209));
        txt_direccion_centroVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccion_centroVacActionPerformed(evt);
            }
        });
        jPanel_centro_vac.add(txt_direccion_centroVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 30));

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(59, 66, 109));
        jLabel18.setText("Nombre:");
        jPanel_centro_vac.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 30));

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(59, 66, 109));
        jLabel19.setText("ID Centro Vacunación:");
        jPanel_centro_vac.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 30));

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(59, 66, 109));
        jLabel20.setText("Dirección:");
        jPanel_centro_vac.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel_centro_vac.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 20, 240));

        jCB_CentroVacunacion_Provincias.setBackground(new java.awt.Color(137, 161, 209));
        jCB_CentroVacunacion_Provincias.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jCB_CentroVacunacion_Provincias.setForeground(new java.awt.Color(59, 66, 109));
        jCB_CentroVacunacion_Provincias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Provincias" }));
        jCB_CentroVacunacion_Provincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_CentroVacunacion_ProvinciasActionPerformed(evt);
            }
        });
        jPanel_centro_vac.add(jCB_CentroVacunacion_Provincias, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 210, 30));

        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(59, 66, 109));
        jLabel23.setText("Provincia:");
        jPanel_centro_vac.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 140, 30));

        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(59, 66, 109));
        jLabel25.setText("Ciudad / Localidad:");
        jPanel_centro_vac.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 140, 32));

        jCB_CentroVacunacion_Ciudades.setBackground(new java.awt.Color(137, 161, 209));
        jCB_CentroVacunacion_Ciudades.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jCB_CentroVacunacion_Ciudades.setForeground(new java.awt.Color(59, 66, 109));
        jCB_CentroVacunacion_Ciudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciudades" }));
        jCB_CentroVacunacion_Ciudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_CentroVacunacion_CiudadesActionPerformed(evt);
            }
        });
        jPanel_centro_vac.add(jCB_CentroVacunacion_Ciudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 210, 32));

        jPanel_titulo_ciudadano1.setBackground(new java.awt.Color(108, 132, 197));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 52, 59));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Formulario Centro Vacunación");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator5.setBackground(new java.awt.Color(48, 52, 59));
        jSeparator5.setForeground(new java.awt.Color(48, 52, 59));

        javax.swing.GroupLayout jPanel_titulo_ciudadano1Layout = new javax.swing.GroupLayout(jPanel_titulo_ciudadano1);
        jPanel_titulo_ciudadano1.setLayout(jPanel_titulo_ciudadano1Layout);
        jPanel_titulo_ciudadano1Layout.setHorizontalGroup(
            jPanel_titulo_ciudadano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel_titulo_ciudadano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_titulo_ciudadano1Layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGap(149, 149, 149))
                .addGroup(jPanel_titulo_ciudadano1Layout.createSequentialGroup()
                    .addGap(271, 271, 271)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGap(269, 269, 269)))
        );
        jPanel_titulo_ciudadano1Layout.setVerticalGroup(
            jPanel_titulo_ciudadano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
            .addGroup(jPanel_titulo_ciudadano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_titulo_ciudadano1Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addGap(3, 3, 3)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel9.setBackground(new java.awt.Color(108, 132, 197));

        jSeparator6.setBackground(new java.awt.Color(48, 52, 59));
        jSeparator6.setForeground(new java.awt.Color(48, 52, 59));

        jBBuscar.setBackground(new java.awt.Color(59, 66, 109));
        jBBuscar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jBBuscar.setForeground(new java.awt.Color(246, 247, 248));
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBModificar.setBackground(new java.awt.Color(59, 66, 109));
        jBModificar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jBModificar.setForeground(new java.awt.Color(246, 247, 248));
        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBEliminar.setBackground(new java.awt.Color(59, 66, 109));
        jBEliminar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jBEliminar.setForeground(new java.awt.Color(246, 247, 248));
        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBGuardar.setBackground(new java.awt.Color(59, 66, 109));
        jBGuardar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(246, 247, 248));
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 437, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 437, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jBBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addGap(122, 122, 122)
                    .addComponent(jBModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(129, 129, 129)
                    .addComponent(jBEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addGap(118, 118, 118)
                    .addComponent(jBGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addGap(53, 53, 53)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(22, 22, 22)))
        );

        javax.swing.GroupLayout jPanel_centroVacLayout = new javax.swing.GroupLayout(jPanel_centroVac);
        jPanel_centroVac.setLayout(jPanel_centroVacLayout);
        jPanel_centroVacLayout.setHorizontalGroup(
            jPanel_centroVacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_titulo_ciudadano1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_centroVacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_centro_vac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_centroVacLayout.setVerticalGroup(
            jPanel_centroVacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_centroVacLayout.createSequentialGroup()
                .addComponent(jPanel_titulo_ciudadano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_centro_vac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Centro Vacunación", jPanel_centroVac);

        jPanel_listar_ciudadano.setBackground(new java.awt.Color(59, 66, 109));

        jPanel7.setBackground(new java.awt.Color(191, 200, 209));

        txt_centroVacunacion_buscar.setBackground(new java.awt.Color(137, 161, 209));

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(59, 66, 109));
        jLabel27.setText("Buscar:");

        jTable_ciudadano_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Centro Vacunación:", "Nombre", "Dirección", "Provincia", "Localidad"
            }
        ));
        jScrollPane1.setViewportView(jTable_ciudadano_tabla);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_centroVacunacion_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_centroVacunacion_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_titulo_ciudadano2.setBackground(new java.awt.Color(108, 132, 197));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(48, 52, 59));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Formulario Ciudadano");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator7.setBackground(new java.awt.Color(48, 52, 59));
        jSeparator7.setForeground(new java.awt.Color(48, 52, 59));

        javax.swing.GroupLayout jPanel_titulo_ciudadano2Layout = new javax.swing.GroupLayout(jPanel_titulo_ciudadano2);
        jPanel_titulo_ciudadano2.setLayout(jPanel_titulo_ciudadano2Layout);
        jPanel_titulo_ciudadano2Layout.setHorizontalGroup(
            jPanel_titulo_ciudadano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel_titulo_ciudadano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_titulo_ciudadano2Layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGap(149, 149, 149))
                .addGroup(jPanel_titulo_ciudadano2Layout.createSequentialGroup()
                    .addGap(271, 271, 271)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGap(269, 269, 269)))
        );
        jPanel_titulo_ciudadano2Layout.setVerticalGroup(
            jPanel_titulo_ciudadano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
            .addGroup(jPanel_titulo_ciudadano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_titulo_ciudadano2Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addGap(3, 3, 3)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel10.setBackground(new java.awt.Color(108, 132, 197));

        jSeparator8.setBackground(new java.awt.Color(48, 52, 59));
        jSeparator8.setForeground(new java.awt.Color(48, 52, 59));

        btn_centroVacunacion_nuevo.setBackground(new java.awt.Color(59, 66, 109));
        btn_centroVacunacion_nuevo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_centroVacunacion_nuevo.setForeground(new java.awt.Color(246, 247, 248));
        btn_centroVacunacion_nuevo.setText("Nuevo");
        btn_centroVacunacion_nuevo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(51, 0, 255)));
        btn_centroVacunacion_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_centroVacunacion_nuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btn_centroVacunacion_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btn_centroVacunacion_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 37, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 36, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel_listar_ciudadanoLayout = new javax.swing.GroupLayout(jPanel_listar_ciudadano);
        jPanel_listar_ciudadano.setLayout(jPanel_listar_ciudadanoLayout);
        jPanel_listar_ciudadanoLayout.setHorizontalGroup(
            jPanel_listar_ciudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_titulo_ciudadano2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_listar_ciudadanoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_listar_ciudadanoLayout.setVerticalGroup(
            jPanel_listar_ciudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listar_ciudadanoLayout.createSequentialGroup()
                .addComponent(jPanel_titulo_ciudadano2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista Centros Vacunación", jPanel_listar_ciudadano);

        javax.swing.GroupLayout jPanel_centroVac_fondoLayout = new javax.swing.GroupLayout(jPanel_centroVac_fondo);
        jPanel_centroVac_fondo.setLayout(jPanel_centroVac_fondoLayout);
        jPanel_centroVac_fondoLayout.setHorizontalGroup(
            jPanel_centroVac_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        jPanel_centroVac_fondoLayout.setVerticalGroup(
            jPanel_centroVac_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_centroVac_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_centroVac_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_direccion_centroVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccion_centroVacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccion_centroVacActionPerformed

    private void btn_centroVacunacion_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_centroVacunacion_nuevoActionPerformed
        if (jPanel_centroVac.isVisible()) {
            jPanel_centroVac.setVisible(false); // Ocultar el JPanel
        } else {
            jPanel_centroVac.setVisible(true); // Mostrar el JPanel
        }
//        jBGuardar.setEnabled(true);
        //ciudadanoControlador.limpiarCampos();
    }//GEN-LAST:event_btn_centroVacunacion_nuevoActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        int id = Integer.parseInt(txt_centroVacunacion_id.getText());
        if (id != 0) {
            CentroVacunacion centroVacunacion = centroVacunacionData.obtenerCentroVacunacionPorId(id);
            if (centroVacunacion != null) {
                txt_nombre_centroVacunacion.setText(centroVacunacion.getNombre());
                txt_direccion_centroVac.setText(centroVacunacion.getDireccion());
                for (int i = 0; i < jCB_CentroVacunacion_Provincias.getItemCount(); i++) {
                    if (centroVacunacion.getProvincia().equals(jCB_CentroVacunacion_Provincias.getItemAt(i).toString())) {
                        jCB_CentroVacunacion_Provincias.setSelectedIndex(i);
                        break;
                    }
                    jCB_CentroVacunacion_Provincias.setSelectedIndex(id);
                }
                for (int i = 0; i < jCB_CentroVacunacion_Ciudades.getItemCount(); i++) {
                    if (centroVacunacion.getCiudad().equals(jCB_CentroVacunacion_Ciudades.getItemAt(i).toString())) {
                        jCB_CentroVacunacion_Ciudades.setSelectedIndex(i);
                        break;
                    }
                    jCB_CentroVacunacion_Ciudades.setSelectedIndex(id);
                }

            } else {
                JOptionPane.showMessageDialog(this, "No existe un centro de vacunacion con ese ID, por favor pruebe nuevamente con otro ID");
            }
        } else {
            JOptionPane.showMessageDialog(this, "El ID no puede ser 0 o un numero negativo");
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        int id = Integer.parseInt(txt_centroVacunacion_id.getText());
        if (id != 0) {
            CentroVacunacion centroVacunacion = centroVacunacionData.obtenerCentroVacunacionPorId(id);
            if (centroVacunacion != null) {
                String nombre = txt_nombre_centroVacunacion.getText();
                String direccion = txt_direccion_centroVac.getText();
                String provincia = jCB_CentroVacunacion_Provincias.getSelectedItem().toString();
                String ciudad = jCB_CentroVacunacion_Ciudades.getSelectedItem().toString();
                centroVacunacion = new CentroVacunacion(id, nombre, direccion, provincia, ciudad);
                centroVacunacionData.modificarCentro(centroVacunacion);
            } else {
                JOptionPane.showMessageDialog(this, "No existe un centro de vacunacion con ese ID, por favor pruebe nuevamente con otro ID");
            }
        } else {
            JOptionPane.showMessageDialog(this, "El ID no puede ser 0 o un numero negativo");
        }

    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        int id = Integer.parseInt(txt_centroVacunacion_id.getText());
        if (id != 0) {
            CentroVacunacion centroVacunacion = centroVacunacionData.obtenerCentroVacunacionPorId(id);
            if (centroVacunacion != null) {
                centroVacunacionData.borrarCentro(id);
            } else {
                JOptionPane.showMessageDialog(this, "No existe un centro de vacunacion con ese ID, por favor pruebe nuevamente con otro ID");
            }
        } else {
            JOptionPane.showMessageDialog(this, "El ID no puede ser 0 o un numero negativo");
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try {
            int id = Integer.parseInt(txt_centroVacunacion_id.getText());
            if (id > 0) {
                JOptionPane.showMessageDialog(this, "Por favor para crear un centro de vacunacion nuevo, deje el campo ID vacio");
            }
        } catch (NumberFormatException ex) {

        }
        int idN = 0;
        String nombre = txt_nombre_centroVacunacion.getText();
        String direccion = txt_direccion_centroVac.getText();
        String provincia = jCB_CentroVacunacion_Provincias.getSelectedItem().toString();
        String ciudad = jCB_CentroVacunacion_Ciudades.getSelectedItem().toString();
        CentroVacunacion centroVacunacion = new CentroVacunacion(idN, nombre, direccion, provincia, ciudad);
        centroVacunacionData.crearCentro(centroVacunacion);
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jCB_CentroVacunacion_ProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_CentroVacunacion_ProvinciasActionPerformed
        if (jCB_CentroVacunacion_Provincias.getSelectedItem() != null) {
            String provinciaSeleccionada = jCB_CentroVacunacion_Provincias.getSelectedItem().toString();
            cargarCiudadesPorProvincia(provinciaSeleccionada);
            jCB_CentroVacunacion_Ciudades.setEnabled(true);  // habilito el ComboBox de ciudades
        }
    }//GEN-LAST:event_jCB_CentroVacunacion_ProvinciasActionPerformed

    private void jCB_CentroVacunacion_CiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_CentroVacunacion_CiudadesActionPerformed

    }//GEN-LAST:event_jCB_CentroVacunacion_CiudadesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_centroVacunacion_nuevo;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    public javax.swing.JComboBox<String> jCB_CentroVacunacion_Ciudades;
    public javax.swing.JComboBox<String> jCB_CentroVacunacion_Provincias;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_centroVac;
    private javax.swing.JPanel jPanel_centroVac_fondo;
    private javax.swing.JPanel jPanel_centro_vac;
    private javax.swing.JPanel jPanel_listar_ciudadano;
    private javax.swing.JPanel jPanel_titulo_ciudadano1;
    private javax.swing.JPanel jPanel_titulo_ciudadano2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTable_ciudadano_tabla;
    public javax.swing.JTextField txt_centroVacunacion_buscar;
    public javax.swing.JTextField txt_centroVacunacion_id;
    public javax.swing.JTextField txt_direccion_centroVac;
    public javax.swing.JTextField txt_nombre_centroVacunacion;
    // End of variables declaration//GEN-END:variables

    private void cargarProvincias() {
        String[] provinciasArgentina = ProvinciasCiudades.obtenerProvinciasArgentina();
        jCB_CentroVacunacion_Provincias.setModel(new DefaultComboBoxModel<>(provinciasArgentina));
    }

//
//         private void initFX() {
//        googleMapPanel = new GoogleMapPanel();
//
//        jPanel_googleMap.setLayout(new BorderLayout());
//        jPanel_googleMap.add(googleMapPanel, BorderLayout.CENTER);
//    }
//         
    private void cargarCiudadesPorProvincia(String provincia) {
        String[] ciudades = ProvinciasCiudades.obtenerCiudadesPorProvincia(provincia);
        jCB_CentroVacunacion_Ciudades.setModel(new DefaultComboBoxModel<>(ciudades));
    }


    
//        private void LlenarTabla() {
//        List<CentroVacunacion> listaCentros = centroVacunacionData.listarCentros();
//        for (CentroVacunacion centro : listaCentros) {
//            modelo.addRow(new Object[]{
//                centro.getIDcentro(),
//                centro.getNombre(),
//                centro.getDireccion(),
//                centro.getProvincia(),
//                centro.getCiudad()
//            });
//        }
//    }
    
  
}
