package vistas2;

import Entidades.Laboratorio;
import accesoADatos.Conexion;
import accesoADatos.LaboratorioData;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilidades.ValidarCUIT;

/**
 *
 * @author Gonz@_
 */
public class LaboratorioVista_2 extends javax.swing.JPanel {

    private LaboratorioData laboratoriodata;
    private Laboratorio laboratorio;
    private Connection con = null;
    DefaultTableModel model = new DefaultTableModel(); //tabla

    /**
     * Creates new form LaboratorioVista_2
     */
    public LaboratorioVista_2() {
        initComponents();
        con = Conexion.getConexion();
        initComponents();
        jLabel_id.setVisible(false);
        laboratoriodata = new LaboratorioData(con);

        laboratorio = new Laboratorio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_laboratorio_fondo = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_laboratorio = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txt_Laboratorio_Cuit = new javax.swing.JTextField();
        txt_laboratorio_nombreLab = new javax.swing.JTextField();
        txt_Laboratorio_pais = new javax.swing.JTextField();
        txt_Laboratorio_domComercial = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel_id = new javax.swing.JLabel();
        jPanel_titulo_ciudadano1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        btn_laboratorio_agregar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        btn_laboratorio_modificar = new javax.swing.JButton();
        btn_laboratorio_eliminar = new javax.swing.JButton();
        btn_buscar_laboratotio = new javax.swing.JButton();

        jP_laboratorio_fondo.setBackground(new java.awt.Color(137, 161, 209));

        jTabbedPane1.setBackground(new java.awt.Color(191, 200, 209));
        jTabbedPane1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        jPanel_laboratorio.setBackground(new java.awt.Color(59, 66, 109));

        jPanel6.setBackground(new java.awt.Color(191, 200, 209));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Laboratorio_Cuit.setBackground(new java.awt.Color(137, 161, 209));
        jPanel6.add(txt_Laboratorio_Cuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, 30));

        txt_laboratorio_nombreLab.setBackground(new java.awt.Color(137, 161, 209));
        jPanel6.add(txt_laboratorio_nombreLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, 30));

        txt_Laboratorio_pais.setBackground(new java.awt.Color(137, 161, 209));
        txt_Laboratorio_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Laboratorio_paisActionPerformed(evt);
            }
        });
        jPanel6.add(txt_Laboratorio_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 30));

        txt_Laboratorio_domComercial.setBackground(new java.awt.Color(137, 161, 209));
        jPanel6.add(txt_Laboratorio_domComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 210, 30));

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(59, 66, 109));
        jLabel18.setText("Nomre Laboratorio");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 30));

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(59, 66, 109));
        jLabel19.setText("CUIT:");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 30));

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(59, 66, 109));
        jLabel20.setText("País:");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, 30));

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(59, 66, 109));
        jLabel22.setText("Dominio Comercial:");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, 30));
        jPanel6.add(jLabel_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 70, 30));

        jPanel_titulo_ciudadano1.setBackground(new java.awt.Color(108, 132, 197));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 52, 59));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Formulario Laboratorio");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator5.setBackground(new java.awt.Color(48, 52, 59));
        jSeparator5.setForeground(new java.awt.Color(48, 52, 59));

        javax.swing.GroupLayout jPanel_titulo_ciudadano1Layout = new javax.swing.GroupLayout(jPanel_titulo_ciudadano1);
        jPanel_titulo_ciudadano1.setLayout(jPanel_titulo_ciudadano1Layout);
        jPanel_titulo_ciudadano1Layout.setHorizontalGroup(
            jPanel_titulo_ciudadano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel_titulo_ciudadano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_titulo_ciudadano1Layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGap(149, 149, 149))
                .addGroup(jPanel_titulo_ciudadano1Layout.createSequentialGroup()
                    .addGap(271, 271, 271)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGap(269, 269, 269)))
        );
        jPanel_titulo_ciudadano1Layout.setVerticalGroup(
            jPanel_titulo_ciudadano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
            .addGroup(jPanel_titulo_ciudadano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_titulo_ciudadano1Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addGap(3, 3, 3)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel9.setBackground(new java.awt.Color(108, 132, 197));

        btn_laboratorio_agregar.setBackground(new java.awt.Color(59, 66, 109));
        btn_laboratorio_agregar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_laboratorio_agregar.setForeground(new java.awt.Color(246, 247, 248));
        btn_laboratorio_agregar.setText("Agregar");
        btn_laboratorio_agregar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(51, 0, 255)));
        btn_laboratorio_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laboratorio_agregarActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(48, 52, 59));
        jSeparator6.setForeground(new java.awt.Color(48, 52, 59));

        btn_laboratorio_modificar.setBackground(new java.awt.Color(59, 66, 109));
        btn_laboratorio_modificar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_laboratorio_modificar.setForeground(new java.awt.Color(246, 247, 248));
        btn_laboratorio_modificar.setText("Modificar");
        btn_laboratorio_modificar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(51, 0, 255)));
        btn_laboratorio_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laboratorio_modificarActionPerformed(evt);
            }
        });

        btn_laboratorio_eliminar.setBackground(new java.awt.Color(59, 66, 109));
        btn_laboratorio_eliminar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_laboratorio_eliminar.setForeground(new java.awt.Color(246, 247, 248));
        btn_laboratorio_eliminar.setText("Eliminar");
        btn_laboratorio_eliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(51, 0, 255)));
        btn_laboratorio_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laboratorio_eliminarActionPerformed(evt);
            }
        });

        btn_buscar_laboratotio.setBackground(new java.awt.Color(59, 66, 109));
        btn_buscar_laboratotio.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_buscar_laboratotio.setForeground(new java.awt.Color(246, 247, 248));
        btn_buscar_laboratotio.setText("Buscar");
        btn_buscar_laboratotio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(51, 0, 255)));
        btn_buscar_laboratotio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_laboratotioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btn_buscar_laboratotio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btn_laboratorio_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(btn_laboratorio_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(104, 104, 104)
                .addComponent(btn_laboratorio_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addGap(58, 58, 58))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_laboratorio_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_laboratorio_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_laboratorio_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_laboratotio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 37, Short.MAX_VALUE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 36, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel_laboratorioLayout = new javax.swing.GroupLayout(jPanel_laboratorio);
        jPanel_laboratorio.setLayout(jPanel_laboratorioLayout);
        jPanel_laboratorioLayout.setHorizontalGroup(
            jPanel_laboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_titulo_ciudadano1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_laboratorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_laboratorioLayout.setVerticalGroup(
            jPanel_laboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_laboratorioLayout.createSequentialGroup()
                .addComponent(jPanel_titulo_ciudadano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Laboratorio", jPanel_laboratorio);

        javax.swing.GroupLayout jP_laboratorio_fondoLayout = new javax.swing.GroupLayout(jP_laboratorio_fondo);
        jP_laboratorio_fondo.setLayout(jP_laboratorio_fondoLayout);
        jP_laboratorio_fondoLayout.setHorizontalGroup(
            jP_laboratorio_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        jP_laboratorio_fondoLayout.setVerticalGroup(
            jP_laboratorio_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_laboratorio_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_laboratorio_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Laboratorio_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Laboratorio_paisActionPerformed

    }//GEN-LAST:event_txt_Laboratorio_paisActionPerformed

    private void btn_laboratorio_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laboratorio_eliminarActionPerformed
        String cuit = txt_Laboratorio_Cuit.getText();

        Laboratorio laboratorio = laboratoriodata.obtenerLaboratorioPorCUIT(cuit);

        if (laboratorio != null) {

            int idLaboratorio = laboratorio.getIdLaboratorio();

            laboratoriodata.eliminarLaboratorio(idLaboratorio);

            JOptionPane.showMessageDialog(null, "Laboratorio eliminado correctamente.");
            limpiarCampos();
        } else {

            JOptionPane.showMessageDialog(null, "Laboratorio no encontrado.", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_laboratorio_eliminarActionPerformed

    private void btn_laboratorio_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laboratorio_agregarActionPerformed
        try {
            // Obtén los datos ingresados por el usuario desde los campos de texto
            String cuitCompleto = txt_Laboratorio_Cuit.getText();
            String nombreLaboratorio = txt_laboratorio_nombreLab.getText();
            String pais = txt_Laboratorio_pais.getText();
            String direccion = txt_Laboratorio_domComercial.getText();

            // Validación del CUIT
            if (!ValidarCUIT.esUnCUITValido(cuitCompleto)) {
                String cuitSinUltimoDigito = cuitCompleto.substring(0, 10);
                int digitoVerificadorCalculado = ValidarCUIT.calcularDigitoVerificador(cuitSinUltimoDigito);
                int option = JOptionPane.showConfirmDialog(
                        null,
                        "El CUIT ingresado es incorrecto. ¿Desea utilizar el CUIT corregido: " + cuitSinUltimoDigito + digitoVerificadorCalculado + "?",
                        "Confirmación",
                        JOptionPane.YES_NO_OPTION
                );
                if (option == JOptionPane.YES_OPTION) {
                    cuitCompleto = cuitSinUltimoDigito + digitoVerificadorCalculado;
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha agregado el laboratorio debido a un CUIT incorrecto.", "", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // Crear un nuevo laboratorio con el ID en este caso se le asigna 0, ya que se generará automáticamente en la base de datos
            Laboratorio laboratorio = new Laboratorio(0, cuitCompleto, nombreLaboratorio, pais, direccion);
            laboratoriodata.agregarLaboratorio(laboratorio);

            JOptionPane.showMessageDialog(null, "Laboratorio agregado correctamente.");
            limpiarCampos();
        } catch (Exception e) {
            System.err.println("Error al agregar laboratorio: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al agregar laboratorio.", "", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_laboratorio_agregarActionPerformed

    private void btn_laboratorio_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laboratorio_modificarActionPerformed

        String cuit = txt_Laboratorio_Cuit.getText();

        Laboratorio laboratorioExistente = laboratoriodata.obtenerLaboratorioPorCUIT(cuit);

        if (laboratorioExistente != null) {

            int idLaboratorio = laboratorioExistente.getIdLaboratorio();

            String nombreLaboratorio = txt_laboratorio_nombreLab.getText();
            String pais = txt_Laboratorio_pais.getText();
            String domComercial = txt_Laboratorio_domComercial.getText();

            Laboratorio laboratorioModificado = new Laboratorio(idLaboratorio, cuit, nombreLaboratorio, pais, domComercial);
            laboratoriodata.actualizarLaboratorio(laboratorioModificado);

            JOptionPane.showMessageDialog(null, "Laboratorio actualizado correctamente.");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Laboratorio no encontrado.", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_laboratorio_modificarActionPerformed

    private void btn_buscar_laboratotioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_laboratotioActionPerformed

        String cuit = txt_Laboratorio_Cuit.getText();

        Laboratorio laboratorio = laboratoriodata.obtenerLaboratorioPorCUIT(cuit);
        if (laboratorio != null) {

            txt_Laboratorio_Cuit.setText(laboratorio.getCuit());
            txt_laboratorio_nombreLab.setText(laboratorio.getNomLaboratorio());
            txt_Laboratorio_pais.setText(laboratorio.getPais());
            txt_Laboratorio_domComercial.setText(laboratorio.getDomComercial());

        } else {

            JOptionPane.showMessageDialog(null, "Laboratorio no encontrado.", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_buscar_laboratotioActionPerformed

    
  public void limpiarCampos() {
    String idLaboratorio = jLabel_id.getText();
    txt_Laboratorio_Cuit.setText(idLaboratorio);
    txt_laboratorio_nombreLab.setText("");
    txt_Laboratorio_pais.setText("");
    txt_Laboratorio_domComercial.setText("");
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_laboratotio;
    public javax.swing.JButton btn_laboratorio_agregar;
    public javax.swing.JButton btn_laboratorio_eliminar;
    public javax.swing.JButton btn_laboratorio_modificar;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel_id;
    private javax.swing.JPanel jP_laboratorio_fondo;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_laboratorio;
    private javax.swing.JPanel jPanel_titulo_ciudadano1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField txt_Laboratorio_Cuit;
    public javax.swing.JTextField txt_Laboratorio_domComercial;
    public javax.swing.JTextField txt_Laboratorio_pais;
    public javax.swing.JTextField txt_laboratorio_nombreLab;
    // End of variables declaration//GEN-END:variables
}
