
package vistas2;

import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Gonz@_
 */
public class PrincipalVG8 extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalVG8
     */
    public PrincipalVG8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jButton_alumno = new javax.swing.JButton();
        jButton_materia = new javax.swing.JButton();
        jButton_administracion = new javax.swing.JButton();
        jButton_consultas = new javax.swing.JButton();
        jButton_salir = new javax.swing.JButton();
        jButton_consultas1 = new javax.swing.JButton();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jL_titulo_sist_ulp = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBackground(new java.awt.Color(0, 0, 204));
        kGradientPanel1.setkEndColor(new java.awt.Color(46, 16, 101));
        kGradientPanel1.setkStartColor(new java.awt.Color(15, 23, 42));

        jButton_alumno.setBackground(new java.awt.Color(30, 41, 59));
        jButton_alumno.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton_alumno.setForeground(new java.awt.Color(232, 242, 208));
        jButton_alumno.setText("Ciudadano");
        jButton_alumno.setAlignmentY(0.0F);
        jButton_alumno.setBorder(null);
        jButton_alumno.setBorderPainted(false);
        jButton_alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_alumno.setDefaultCapable(false);
        jButton_alumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_alumno.setIconTextGap(0);
        jButton_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alumnoActionPerformed(evt);
            }
        });

        jButton_materia.setBackground(new java.awt.Color(30, 41, 59));
        jButton_materia.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton_materia.setForeground(new java.awt.Color(232, 242, 208));
        jButton_materia.setText("Laboratorio");
        jButton_materia.setAlignmentY(0.0F);
        jButton_materia.setBorder(null);
        jButton_materia.setBorderPainted(false);
        jButton_materia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_materia.setDefaultCapable(false);
        jButton_materia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_materia.setIconTextGap(0);
        jButton_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_materiaActionPerformed(evt);
            }
        });

        jButton_administracion.setBackground(new java.awt.Color(30, 41, 59));
        jButton_administracion.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton_administracion.setForeground(new java.awt.Color(232, 242, 208));
        jButton_administracion.setText("Vacuna");
        jButton_administracion.setAlignmentY(0.0F);
        jButton_administracion.setBorder(null);
        jButton_administracion.setBorderPainted(false);
        jButton_administracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_administracion.setDefaultCapable(false);
        jButton_administracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_administracion.setIconTextGap(0);
        jButton_administracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_administracionActionPerformed(evt);
            }
        });

        jButton_consultas.setBackground(new java.awt.Color(30, 41, 59));
        jButton_consultas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton_consultas.setForeground(new java.awt.Color(232, 242, 208));
        jButton_consultas.setText("Cita Vacunación");
        jButton_consultas.setAlignmentY(0.0F);
        jButton_consultas.setBorder(null);
        jButton_consultas.setBorderPainted(false);
        jButton_consultas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_consultas.setDefaultCapable(false);
        jButton_consultas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_consultas.setIconTextGap(0);
        jButton_consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultasActionPerformed(evt);
            }
        });

        jButton_salir.setBackground(new java.awt.Color(30, 41, 59));
        jButton_salir.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton_salir.setForeground(new java.awt.Color(232, 242, 208));
        jButton_salir.setText("Salir");
        jButton_salir.setAlignmentY(0.0F);
        jButton_salir.setBorder(null);
        jButton_salir.setBorderPainted(false);
        jButton_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_salir.setDefaultCapable(false);
        jButton_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_salir.setIconTextGap(0);
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });

        jButton_consultas1.setBackground(new java.awt.Color(30, 41, 59));
        jButton_consultas1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton_consultas1.setForeground(new java.awt.Color(232, 242, 208));
        jButton_consultas1.setText("Centro de Vacunción");
        jButton_consultas1.setAlignmentY(0.0F);
        jButton_consultas1.setBorder(null);
        jButton_consultas1.setBorderPainted(false);
        jButton_consultas1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_consultas1.setDefaultCapable(false);
        jButton_consultas1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_consultas1.setIconTextGap(0);
        jButton_consultas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addComponent(jButton_consultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_consultas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_administracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_materia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_alumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton_alumno, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_materia, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_administracion, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_consultas1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_consultas, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addComponent(jButton_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 210, 600));

        kGradientPanel3.setkEndColor(new java.awt.Color(15, 23, 42));
        kGradientPanel3.setkGradientFocus(800);
        kGradientPanel3.setkStartColor(new java.awt.Color(30, 41, 59));

        jL_titulo_sist_ulp.setBackground(new java.awt.Color(51, 51, 51));
        jL_titulo_sist_ulp.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 36)); // NOI18N
        jL_titulo_sist_ulp.setForeground(new java.awt.Color(232, 242, 208));
        jL_titulo_sist_ulp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_titulo_sist_ulp.setText("Sistema de Vacunación");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jL_titulo_sist_ulp, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                    .addContainerGap(14, Short.MAX_VALUE)
                    .addComponent(jL_titulo_sist_ulp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel1.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 890, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alumnoActionPerformed
        //        // remuev el  panel que hay en jPanel_desktop
        //        jPanel_desktop.removeAll();
        //        // agreg0 el panel  alumno al jPanel desktop
        //        jPanel_desktop.add(alumnoPanel, BorderLayout.CENTER);
        //        alumnoPanel.setVisible(true);
        //        // revalida y repinta el jPanel desktop para que se muestre el nuevo panel
        //        jPanel_desktop.revalidate();
        //        jPanel_desktop.repaint();
    }//GEN-LAST:event_jButton_alumnoActionPerformed

    private void jButton_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_materiaActionPerformed
        //        jPanel_desktop.removeAll();
        //        jPanel_desktop.add(materiaPanel, BorderLayout.CENTER);
        //        materiaPanel.setVisible(true);
        //        jPanel_desktop.revalidate();
        //        jPanel_desktop.repaint();
    }//GEN-LAST:event_jButton_materiaActionPerformed

    private void jButton_administracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_administracionActionPerformed
        //        jPanel_desktop.removeAll();
        //        jPanel_desktop.add(administracionPanel, BorderLayout.CENTER);
        //        administracionPanel.setVisible(true);
        //        jPanel_desktop.revalidate();
        //        jPanel_desktop.repaint();
    }//GEN-LAST:event_jButton_administracionActionPerformed

    private void jButton_consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultasActionPerformed
        //        jPanel_desktop.removeAll();
        //        jPanel_desktop.add(consultasPanel, BorderLayout.CENTER);
        //        consultasPanel.setVisible(true);
        //        jPanel_desktop.revalidate();
        //        jPanel_desktop.repaint();
    }//GEN-LAST:event_jButton_consultasActionPerformed

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        //        int confirmacion = JOptionPane.showConfirmDialog(
            //            this, "¿Seguro que deseas salir?", "Salida", JOptionPane.YES_NO_OPTION);
        //
        //        if (confirmacion == JOptionPane.YES_OPTION) {
            //            jPanel_desktop.removeAll();
            //            jPanel_desktop.add(jD_desktop, BorderLayout.CENTER);
            //            jD_desktop.setVisible(true);
            //
            //            this.dispose(); // cierra la ventana en la que estamos
            //            //nos vemos en disny!
            //            System.exit(0);
            //        }
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jButton_consultas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_consultas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            UIManager.setLookAndFeel(new McWinLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        // crea e inicializa el  principal
        java.awt.EventQueue.invokeLater(() -> {
         PrincipalVG8 principalVG8 = new PrincipalVG8();  // misma intancia
         principalVG8.setVisible(true);
        });
        
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PrincipalVG8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PrincipalVG8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PrincipalVG8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PrincipalVG8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PrincipalVG8().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_administracion;
    public javax.swing.JButton jButton_alumno;
    public javax.swing.JButton jButton_consultas;
    public javax.swing.JButton jButton_consultas1;
    public javax.swing.JButton jButton_materia;
    public javax.swing.JButton jButton_salir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jL_titulo_sist_ulp;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel3;
    // End of variables declaration//GEN-END:variables
}
