package vistas2;

import Entidades.Vacuna;
import accesoADatos.VacunaData;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.lang.Integer;
import java.sql.Date;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

public class VacunaVista extends javax.swing.JPanel {

    private VacunaData vacunaData = new VacunaData();
    private Vacuna vacunActual = null;
    private Vacuna borrar = null;
    private Vacuna vacunaEncontrada = null;
    private Connection conexion = null;
    private boolean colocada;
    private String[] marcas = {"Moderna", "Pfizer", "AstraZeneca", "Sinopharm", "Sputnik"};
    private String[] medidas = {"0.3", "0.5", "0.9"};

    public VacunaVista() {
        initComponents();
        cargarMarcas();
        cargarMedidas();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colocadaSiNo = new javax.swing.ButtonGroup();
        vistaVacuna = new javax.swing.JPanel();
        jTabbedPane1_vac = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jText_numSerie = new javax.swing.JTextField();
        jComboBox1_Marca = new javax.swing.JComboBox<>();
        jComboBox2_Medida = new javax.swing.JComboBox<>();
        jButton1_Agregar = new javax.swing.JButton();
        jButton2_Buscar = new javax.swing.JButton();
        jButton3_Modificar = new javax.swing.JButton();
        jButton4_Eliminar = new javax.swing.JButton();
        jRadioButtonSi = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jCFechaCad = new com.toedter.calendar.JCalendar();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Colocada");

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Marca");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Medida");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Vencimiento");

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("N°de Serie");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Formulario Vacuna");

        jText_numSerie.setBackground(new java.awt.Color(102, 153, 255));

        jComboBox1_Marca.setBackground(new java.awt.Color(102, 153, 255));
        jComboBox1_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jComboBox2_Medida.setBackground(new java.awt.Color(102, 153, 255));

        jButton1_Agregar.setBackground(new java.awt.Color(51, 102, 255));
        jButton1_Agregar.setForeground(new java.awt.Color(204, 255, 255));
        jButton1_Agregar.setText("Agregar");
        jButton1_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_AgregarActionPerformed(evt);
            }
        });

        jButton2_Buscar.setBackground(new java.awt.Color(51, 102, 255));
        jButton2_Buscar.setForeground(new java.awt.Color(204, 255, 255));
        jButton2_Buscar.setText("Buscar");
        jButton2_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_BuscarActionPerformed(evt);
            }
        });

        jButton3_Modificar.setBackground(new java.awt.Color(51, 102, 255));
        jButton3_Modificar.setForeground(new java.awt.Color(204, 255, 255));
        jButton3_Modificar.setText("Modificar");
        jButton3_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_ModificarActionPerformed(evt);
            }
        });

        jButton4_Eliminar.setBackground(new java.awt.Color(51, 102, 255));
        jButton4_Eliminar.setForeground(new java.awt.Color(204, 255, 255));
        jButton4_Eliminar.setText("Eliminar");
        jButton4_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_EliminarActionPerformed(evt);
            }
        });

        jRadioButtonSi.setBackground(new java.awt.Color(204, 204, 204));
        colocadaSiNo.add(jRadioButtonSi);
        jRadioButtonSi.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButtonSi.setText("SI");
        jRadioButtonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSiActionPerformed(evt);
            }
        });

        jRadioButtonNo.setBackground(new java.awt.Color(204, 204, 204));
        colocadaSiNo.add(jRadioButtonNo);
        jRadioButtonNo.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButtonNo.setText("NO");
        jRadioButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addComponent(jLabel2))
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jText_numSerie)
                                    .addComponent(jComboBox1_Marca, 0, 429, Short.MAX_VALUE)
                                    .addComponent(jComboBox2_Medida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(101, 101, 101))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButtonNo))
                                    .addComponent(jCFechaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3_Modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1_Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jText_numSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_Agregar))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2_Buscar))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2_Medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3_Modificar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton4_Eliminar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCFechaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonSi)
                        .addComponent(jRadioButtonNo)))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout vistaVacunaLayout = new javax.swing.GroupLayout(vistaVacuna);
        vistaVacuna.setLayout(vistaVacunaLayout);
        vistaVacunaLayout.setHorizontalGroup(
            vistaVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1_vac, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(vistaVacunaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        vistaVacunaLayout.setVerticalGroup(
            vistaVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaVacunaLayout.createSequentialGroup()
                .addComponent(jTabbedPane1_vac, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaVacuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaVacuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoActionPerformed

        //        if (jRadioButtonNo.isSelected()) {   // "Prioritario" está seleccionado, habilita la caja de texto
        //            colocada = true;
        //        }
    }//GEN-LAST:event_jRadioButtonNoActionPerformed

    private void jRadioButtonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSiActionPerformed

        //        if (jRadioButtonSi.isSelected()) {   // "Prioritario" está seleccionado, habilita la caja de texto
        //            colocada = true;
        //        }
    }//GEN-LAST:event_jRadioButtonSiActionPerformed

//BOTON ELIMINAR
    private void jButton4_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_EliminarActionPerformed

        Vacuna vacunActual = null;
        int nroSerieDosis;
        try {
            nroSerieDosis = Integer.parseInt(jText_numSerie.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El n° de Serie debe contener solo numeros");
            return;
        }
        Vacuna vacunaEncontrada = vacunaData.obtenerVacunaPorNroSerie(nroSerieDosis);

        if (vacunaEncontrada != null) {
            boolean colocada = true;
            if (vacunActual == null) {
                vacunActual = new Vacuna(nroSerieDosis, vacunaEncontrada.getMarca(), vacunaEncontrada.getMedida(), vacunaEncontrada.getFechaCaduca(), colocada);
            }
            vacunaData.modificarStockVacunas(vacunActual);
            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Vacuna modificada con éxito");

        } else {
            JOptionPane.showMessageDialog(this, "Vacuna no encontrada!");
        }
    }//GEN-LAST:event_jButton4_EliminarActionPerformed

//BOTON MODIFICAR    
    private void jButton3_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_ModificarActionPerformed

        Vacuna vacunActual = null;
        int nroSerieDosis;
        try {
            nroSerieDosis = Integer.parseInt(jText_numSerie.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El n° de Serie debe contener solo numeros");
            return;
        }
        Vacuna vacunaEncontrada = vacunaData.obtenerVacunaPorNroSerie(nroSerieDosis);

        if (vacunaEncontrada != null) {
            String marca = jComboBox1_Marca.getSelectedItem().toString();
            double medida = Double.parseDouble(jComboBox2_Medida.getSelectedItem().toString());
            java.util.Date utilDate = jCFechaCad.getDate();
            if (utilDate != null) {
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                boolean colocada = jRadioButtonSi.isSelected();

                if (vacunActual == null) {
                    vacunActual = new Vacuna(nroSerieDosis, marca, medida, sqlDate, colocada);
                }

                vacunaData.modificarStockVacunas(vacunActual);

                limpiarCampos();

                JOptionPane.showMessageDialog(this, "Vacuna modificada con éxito");

            } else {
                JOptionPane.showMessageDialog(this, "Vacuna no encontrada!");
            }
        }
    }//GEN-LAST:event_jButton3_ModificarActionPerformed

//BOTON BUSCAR    
    private void jButton2_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_BuscarActionPerformed

        int nroSerieDosis;
        try {
            nroSerieDosis = Integer.parseInt(jText_numSerie.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El n° de Serie debe contener solo numeros");
            return;
        }
        Vacuna vacunaEncontrada = vacunaData.obtenerVacunaPorNroSerie(nroSerieDosis);

        //        JOptionPane.showMessageDialog(this, vacunaEncontrada);   // para ver si llega vacuna de la BD
        if (vacunaEncontrada != null) {
            jComboBox1_Marca.setSelectedItem(vacunaEncontrada.getMarca());

            for (int i = 0; i < jComboBox1_Marca.getItemCount(); i++) {
                if (vacunaEncontrada.getMarca().equals(jComboBox1_Marca.getItemAt(i))) {

                    jComboBox1_Marca.setSelectedIndex(i);
                    break;
                }
            }

            jComboBox2_Medida.setSelectedItem(vacunaEncontrada.getMedida());

            for (int i = 0; i < jComboBox2_Medida.getItemCount(); i++) {
                if (vacunaEncontrada.getMedida() == (Double.valueOf(jComboBox2_Medida.getItemAt(i)))) {
                    jComboBox2_Medida.setSelectedIndex(i);
                    break;
                }
            }

            jCFechaCad.setDate(vacunaEncontrada.getFechaCaduca());

            if (vacunaEncontrada.isColocada() == true) {
                jRadioButtonSi.setSelected(true);

            } else {
                jRadioButtonNo.setSelected(true);
            }

            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(this, "Vacuna no encontrada!");
        }
    }//GEN-LAST:event_jButton2_BuscarActionPerformed

//BOTON AGREGAR    
    private void jButton1_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_AgregarActionPerformed

        int nroSerieDosis = 0;
        try {
            nroSerieDosis = Integer.parseInt(jText_numSerie.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El n° de Serie debe contener solo numeros");
        }
        String marca = jComboBox1_Marca.getSelectedItem().toString();
        double medida = Double.parseDouble(jComboBox2_Medida.getSelectedItem().toString());
        java.util.Date utilDate = jCFechaCad.getDate();
        if (utilDate != null) {
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            boolean colocada = jRadioButtonSi.isSelected();
            if (vacunActual == null) {
                vacunActual = new Vacuna(nroSerieDosis, marca, medida, sqlDate, colocada);
            }

            vacunaData.cargarVacunas(vacunActual);

            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "La fecha de caducidad no está seleccionada");
        }

    }//GEN-LAST:event_jButton1_AgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup colocadaSiNo;
    private javax.swing.JButton jButton1_Agregar;
    private javax.swing.JButton jButton2_Buscar;
    private javax.swing.JButton jButton3_Modificar;
    private javax.swing.JButton jButton4_Eliminar;
    private com.toedter.calendar.JCalendar jCFechaCad;
    private javax.swing.JComboBox<String> jComboBox1_Marca;
    private javax.swing.JComboBox<String> jComboBox2_Medida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonSi;
    private javax.swing.JTabbedPane jTabbedPane1_vac;
    private javax.swing.JTextField jText_numSerie;
    private javax.swing.JPanel vistaVacuna;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Crea el JFrame para mostrar el JPanel
                JFrame frame = new JFrame("Carga de Provincias");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(900, 500);

                // Crea y agrega el panel al frame
                VacunaVista vacuna = new VacunaVista();
                frame.add(vacuna);

                // Haz visible el frame
                frame.setVisible(true);
            }
        });
    }

    private void cargarMarcas() {
        jComboBox1_Marca.setModel(new DefaultComboBoxModel<>(marcas));
    }

    private void cargarMedidas() {
        jComboBox2_Medida.setModel(new DefaultComboBoxModel<>(medidas));
    }

}
